# Generated by Django 5.1.2 on 2024-11-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название фильма')),
                ('short_description', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('text', models.TextField(verbose_name='Отзыв')),
            ],
        ),
    ]
